---
# Ansible Inventory - Managed hosts for homelab automation
# Currently managing: x202 (primary web services)
# Extensible: add new hosts following x202 pattern

all:
  children:
    # Virtual Machines
    vms:
      hosts:
        x202:
          ansible_host: 192.168.0.202
          compose_style: pve/x202
          services_base_path: /home/code/docker/config

    # Functional Groups
    web_vms:
      hosts:
        x202:

    # All Docker hosts (for group operations)
    docker_hosts:
      children:
        vms:

  vars:
    ansible_user: code
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
