title: Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: dot
showStats: true

layout:
  x000 (Control Node):
    icon: mdi-server-network
    style: column
  x202 (Primary):
    icon: mdi-database
    style: column
  x203 (Gaming):
    icon: mdi-gamepad-variant
    style: column
  Infrastructure:
    icon: mdi-cloud-cog
    style: column
