title: Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: dot
showStats: true

layout:
  Control Node:
    icon: mdi-server-network
  Databases:
    icon: mdi-database
  Monitoring:
    icon: mdi-chart-line
  Gaming:
    icon: mdi-gamepad-variant
  Infrastructure:
    icon: mdi-cloud-cog
