http:
  #region routers
  routers:
    dev:
      entryPoints:
        - "https"
      rule: "Host(`dev.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: dev3000
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pihole
    portainer:
      entryPoints:
        - "https"
      rule: "Host(`portainer.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: portainer
    wakapi:
      entryPoints:
        - "https"
      rule: "Host(`wakapi.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: wakapi
    grafana:
      entryPoints:
        - "https"
      rule: "Host(`grafana.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: grafana
    glitchtip:
      entryPoints:
        - "https"
      rule: "Host(`glitchtip.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: glitchtip
    passbolt:
      entryPoints:
        - "https"
      rule: "Host(`passbolt.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: passbolt
    samba:
      entryPoints:
        - "https"
      rule: "Host(`samba.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: samba
    romm:
      entryPoints:
        - "https"
      rule: "Host(`retro.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: romm
    qt:
      entryPoints:
        - "https"
      rule: "Host(`qt.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: qt
    chrome:
      entryPoints:
        - "https"
      rule: "Host(`chrome.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: chrome

  #endregion
  #region services
  services:
    dev3000:
      loadBalancer:
        servers:
          - url: "http://192.168.0.250:3000"
        passHostHeader: true
    dev4200:
      loadBalancer:
        servers:
          - url: "http://192.168.0.250:4200"
        passHostHeader: true
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.0.200:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.0.100"
        passHostHeader: true
    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.0.102:9443"
        passHostHeader: true
    wakapi:
      loadBalancer:
        servers:
          - url: "http://192.168.0.104:3000"
        passHostHeader: true
    grafana:
      loadBalancer:
        servers:
          - url: "http://192.168.0.107:3000"
        passHostHeader: true
    glitchtip:
      loadBalancer:
        servers:
          - url: "http://192.168.0.105:8000"
        passHostHeader: true
    passbolt:
      loadBalancer:
        servers:
          - url: "http://192.168.0.108"
        passHostHeader: true
    samba:
      loadBalancer:
        servers:
          - url: "http://192.168.0.109"
        passHostHeader: true
    romm:
      loadBalancer:
        servers:
          - url: "http://192.168.0.111"
        passHostHeader: true
    qt:
      loadBalancer:
        servers:
          - url: "http://192.168.0.112:8080"
        passHostHeader: true
    chrome:
      loadBalancer:
        servers:
          - url: "http://192.168.0.112:3000"
        passHostHeader: true
  #endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
          - "192.168.0.0/16"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
