---
services:
  qt:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qt
    labels:
      deunhealth.restart.on.unhealthy: true
    depends_on:
      gluetun:
        condition: service_healthy
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6881
    network_mode: service:gluetun
    volumes:
      - ../../data/qt/config:/config
      - /mnt/qt/downloads:/downloads
    # ports:
    #   - 8081:8081
    #   - 6881:6881
    #   - 6881:6881/udp
    restart: unless-stopped
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8081:8081 # qbittorrent web interface
      - 6881:6881 # qbittorrent torrent port
      - 6881:6881/udp
      - 3000:3000
      - 3001:3001
      - 8080:8080
    volumes:
      - ../../data/gluetun:/gluetun
    env_file: .env
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - SERVER_CITIES=${SERVER_CITIES}
      - HEALTH_VPN_DURATION_INITIAL=${HEALTH_VPN_DURATION_INITIAL}
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    network_mode: 'none'
    env_file: .env
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=${TZ}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    network_mode: service:gluetun
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - FILE_MANAGER_PATH=/mnt/qt/downloads
      - CHROME_CLI=https://ipleak.net/
      - LC_ALL=en_US.UTF-8
      - DRI_NODE=/dev/dri/renderD128
    env_file: .env
    # tmpfs:
    # - /config:size=1G
    volumes:
      - /mnt/qt/browser/config:/config
      - /mnt/qt/downloads:/mnt/downloads
    # ports:
    #   - 3000:3000
    #   - 3001:3001
    shm_size: '2gb'
    restart: unless-stopped

  romifleur:
    image: ghcr.io/4sitam4/romifleur:latest
    container_name: romifleur
    network_mode: service:gluetun
    user: '${UID:-1000}:${GID:-1000}'
    depends_on:
      gluetun:
        condition: service_healthy
    # ports:
    # - "8080:8080"
    volumes:
      - /mnt/retro/library/roms:/app/data
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - 8083:80
    volumes:
      - /mnt:/srv
      - ../../data/filebrowser/database:/database
      - ../../data/filebrowser/config:/config
    restart: unless-stopped

  romm:
    image: rommapp/romm:latest
    container_name: romm
    restart: unless-stopped
    user: '${UID:-1000}:${GID:-1000}'
    env_file: .env
    environment:
      - DB_HOST=romm-db
      - DB_NAME=${DB_NAME} # Should match MYSQL_DATABASE in mariadb
      - DB_USER=${DB_USER} # Should match MYSQL_USER in mariadb
      - DB_PASSWD=${DB_PASSWD} # Should match MYSQL_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID} # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET=${IGDB_CLIENT_SECRET} # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY=${MOBYGAMES_API_KEY} # https://www.mobygames.com/info/api/
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY} # https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb
      - RETROACHIEVEMENTS_API_KEY=${RETROACHIEVEMENTS_API_KEY}
      - LAUNCHBOX_API_ENABLED=${LAUNCHBOX_API_ENABLED} # Set to "true" to enable LaunchBox API integration
      - PLAYMATCH_API_ENABLED=${PLAYMATCH_API_ENABLED} # Set to "true" to enable PlayMatch API integration
      - HASHEOUS_API_ENABLED=${HASHEOUS_API_ENABLED} # Set to "true" to enable Hasheous API integration
      - FLASHPOINT_API_ENABLED=${FLASHPOINT_API_ENABLED} # Set to "true" to enable Flashpoint API integration
      - HLTB_API_ENABLED=${HLTB_API_ENABLED} # Set to "true" to enable HowLongToBeat API integration
    volumes:
      - romm_redis_data:/redis-data # Cached data for background tasks
      - /mnt/retro/library:/romm/library # Your game library
      - /mnt/retro/romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /mnt/retro/romm/assets:/romm/assets # Uploaded saves, states, etc.
      - /mnt/retro/romm/config:/romm/config # Path where config.yml is stored
    ports:
      - 80:8080
    depends_on:
      romm-db:
        condition: service_healthy

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
  romm_redis_data:
