---
services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY}
      SEMAPHORE_LDAP_ACTIVATED: 'no'
      SEMAPHORE_WEB_HOST: ${SEMAPHORE_WEB_HOST}
      TZ: ${TIMEZONE:-Europe/Warsaw}
    volumes:
      - ${SEMAPHORE_DATA_DIR:-/opt/semaphore}/config:/etc/semaphore:z
      - ${SEMAPHORE_DATA_DIR:-/opt/semaphore}/tmp:/tmp/semaphore:z
      - ${REPO_PATH}:/repo:ro
    networks:
      - homelab

networks:
  homelab:
    name: homelab
    external: true
