---
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.0
    ports:
      - 3002:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GRAFANA_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_AUTH_ANONYMOUS_ENABLED=${GRAFANA_AUTH_ANONYMOUS_ENABLED}
      - GF_AUTH_BASIC_ENABLED=${GRAFANA_AUTH_BASIC_ENABLED}
      - GF_SERVER_SERVE_FROM_SUB_PATH=${GRAFANA_SERVER_SERVE_FROM_SUB_PATH}
    volumes:
      - ./provisioning:/etc/grafana/provisioning/
    networks:
      - grafana_network
      - caddy_network
    restart: unless-stopped

networks:
  grafana_network:
    name: grafana_network
    driver: bridge
  caddy_network:
    name: caddy_network
    external: true