x-glitchtip-environment: &glitchtip-environment
  DATABASE_URL: ${GLITCHTIP_DATABASE_URL}
  SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
  PORT: ${GLITCHTIP_PORT}
  EMAIL_URL: ${GLITCHTIP_EMAIL_URL}
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
  DEFAULT_FROM_EMAIL: ${GLITCHTIP_DEFAULT_FROM_EMAIL}
  CELERY_WORKER_AUTOSCALE: ${GLITCHTIP_CELERY_WORKER_AUTOSCALE}
  CELERY_WORKER_MAX_TASKS_PER_CHILD: ${GLITCHTIP_CELERY_WORKER_MAX_TASKS_PER_CHILD}
  CSP_DEFAULT_SRC: ${GLITCHTIP_CSP_DEFAULT_SRC}
  REDIS_URL: ${GLITCHTIP_REDIS_URL}

services:
  glitchtip_web:
    container_name: glitchtip_web
    image: glitchtip/glitchtip:v5.1.1
    depends_on:
      - glitchtip_db
    ports:
      - 8000:8000
    environment: *glitchtip-environment
    volumes:
      - glitchtip_uploads:/code/uploads
    restart: unless-stopped
    networks:
      - caddy_network

  glitchtip_worker:
    container_name: glitchtip_worker
    image: glitchtip/glitchtip:v5.1.1
    depends_on:
      - glitchtip_db
    command: ./bin/run-celery-with-beat.sh
    environment: *glitchtip-environment
    volumes:
      - glitchtip_uploads:/code/uploads
    restart: unless-stopped
    networks:
      - caddy_network

  glitchtip_migrate:
    container_name: glitchtip_migrate
    image: glitchtip/glitchtip:v5.1.1
    depends_on:
      - glitchtip_db
    command: ./bin/run-migrate.sh
    environment: *glitchtip-environment
    networks:
      - caddy_network

  glitchtip_db:
    image: postgres:16
    container_name: glitchtip_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - glitchtip_db:/var/lib/postgresql
      - glitchtip_db_data:/var/lib/postgresql/data
    networks:
      - caddy_network

volumes:
  glitchtip_uploads:
    name: glitchtip_uploads
    driver: local
  glitchtip_db:
    name: glitchtip_db
    driver: local
  glitchtip_db_data:
    name: glitchtip_db_data
    driver: local

networks:
  caddy_network:
    name: caddy_network
    external: true
  postgres_network:
    name: postgres_network
    external: true